---
# Configuration file for MegaLinter
# See all available variables at https://megalinter.github.io/configuration/ and in linters documentation
APPLY_FIXES: none
SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false
ENABLE: [JAVASCRIPT, CSS, HTML, JSON, YAML, JSX]
DISABLE_LINTERS: [JAVASCRIPT_STANDARD, CSS_SCSS_LINT, YAML_PRETTIER]
SHOW_SKIPPED_LINTERS: false
