name: Run Linters
on:
  push:
    branches:
      - master
      - react
  pull_request_target:
    branches:
      - master
      - react

permissions:
  issues: write
  pull-requests: write
  discussions: write
  checks: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - name: Install Linters
      run: npm i --legacy-peer-deps -D eslint prettier
    - uses: wearerequired/lint-action@v1
      name: Lint
      with:
        eslint: true
        eslint_args: "--max-warnings 0"
        prettier: true